// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AutoUploadService 自动上传服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChangeDetailImage 在详情弹窗中更换图片
 * 流程：悬停图片 -> 点击"更换图片" -> 点击"本地上传" -> 设置图片
 */
export function ChangeDetailImage(imagePath: string): $CancellablePromise<void> {
    return $Call.ByID(1365364699, imagePath);
}

/**
 * ClickEditDescription 点击"编辑描述"按钮并等待弹窗出现
 */
export function ClickEditDescription(): $CancellablePromise<void> {
    return $Call.ByID(2612800021);
}

/**
 * ClickFirstImageItem 点击编辑器中的第一个图片项
 */
export function ClickFirstImageItem(): $CancellablePromise<void> {
    return $Call.ByID(655872053);
}

/**
 * CloseBrowser 关闭浏览器
 */
export function CloseBrowser(): $CancellablePromise<void> {
    return $Call.ByID(1930944195);
}

/**
 * ConfirmLogin 前端调用此方法确认登录完成
 */
export function ConfirmLogin(): $CancellablePromise<void> {
    return $Call.ByID(1538631554);
}

/**
 * FillProductInfo 填写产品信息（店小秘平台）
 * productID 是素材编号，用于从合成目录查找图片
 */
export function FillProductInfo(productID: string, product: $models.ProductInfo): $CancellablePromise<void> {
    return $Call.ByID(2027383609, productID, product);
}

/**
 * InitBrowser 初始化浏览器
 */
export function InitBrowser(): $CancellablePromise<void> {
    return $Call.ByID(3458457303);
}

/**
 * Login 登录到店小秘平台（支持人工处理验证码）
 */
export function Login(config: $models.LoginConfig): $CancellablePromise<void> {
    return $Call.ByID(790496448, config);
}

/**
 * NavigateToProductPage 导航到产品编辑页面
 */
export function NavigateToProductPage(productID: string): $CancellablePromise<void> {
    return $Call.ByID(2808482315, productID);
}

/**
 * PublishProduct 悬浮在发布按钮上，然后点击立即发布
 */
export function PublishProduct(): $CancellablePromise<void> {
    return $Call.ByID(1360861969);
}

/**
 * UploadProductDianxiaomi 店小秘平台自动上传商品
 * 注意：此方法不会自动关闭浏览器，上传完成后需要手动调用 CloseBrowser() 关闭
 */
export function UploadProductDianxiaomi(loginConfig: $models.LoginConfig, productID: string, product: $models.ProductInfo): $CancellablePromise<$models.UploadResult | null> {
    return $Call.ByID(2412333456, loginConfig, productID, product).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UploadProductsDianxiaomi 批量上传多个商品到店小秘
 * 注意：此方法不会自动关闭浏览器，上传完成后需要手动调用 CloseBrowser() 关闭
 */
export function UploadProductsDianxiaomi(loginConfig: $models.LoginConfig, products: { [_ in string]?: $models.ProductInfo }): $CancellablePromise<($models.UploadResult | null)[]> {
    return $Call.ByID(1050910047, loginConfig, products).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.UploadResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
