// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddTemplate 添加图片模板
 */
export function AddTemplate(name: string, width: number, height: number, scale: number, imagePath: string, offsetTop: number, offsetRight: number, offsetBottom: number, offsetLeft: number): $CancellablePromise<string> {
    return $Call.ByID(3594976957, name, width, height, scale, imagePath, offsetTop, offsetRight, offsetBottom, offsetLeft);
}

/**
 * CombineImages 使用一个或多个模板合成多张图片，并保存到当前目录下的"合成"目录
 * 返回本次合成结果所在的目录路径
 */
export function CombineImages(templateIDs: string[], sourcePaths: string[]): $CancellablePromise<string> {
    return $Call.ByID(2620603867, templateIDs, sourcePaths);
}

/**
 * CombineImagesWithTemplates 使用模板信息合成多张图片
 * 返回本次合成结果所在的目录路径
 */
export function CombineImagesWithTemplates(templateInfos: $models.TemplateInfo[], materials: $models.MaterialInfo[]): $CancellablePromise<string> {
    return $Call.ByID(2420510374, templateInfos, materials);
}

/**
 * CountCombinedImagesByMaterialCodes 统计当前合成目录下每个素材编号对应的合成图片数量
 */
export function CountCombinedImagesByMaterialCodes(materialCodes: string[]): $CancellablePromise<{ [_ in string]?: number }> {
    return $Call.ByID(3337528772, materialCodes).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteTemplate 删除模板
 */
export function DeleteTemplate(id: string): $CancellablePromise<void> {
    return $Call.ByID(3400298829, id);
}

/**
 * GetImageBase64 读取图片并转换为 base64，支持本地路径和 URL
 */
export function GetImageBase64(imagePath: string): $CancellablePromise<string> {
    return $Call.ByID(724105266, imagePath);
}

/**
 * GetTemplates 获取所有模板
 */
export function GetTemplates(): $CancellablePromise<$models.ImageTemplate[]> {
    return $Call.ByID(3190505947).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SaveImageToCurrentFolder 保存图片到当前文件夹
 */
export function SaveImageToCurrentFolder(sourcePath: string): $CancellablePromise<string> {
    return $Call.ByID(2315094336, sourcePath);
}

/**
 * SelectImage 选择图片文件
 */
export function SelectImage(): $CancellablePromise<string> {
    return $Call.ByID(1689630681);
}

/**
 * SelectImages 选择多张图片文件
 */
export function SelectImages(): $CancellablePromise<string[]> {
    return $Call.ByID(873472158).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.ImageTemplate.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
