// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * ImageTemplate 图片模板结构
 */
export class ImageTemplate {
    "id": string;
    "name": string;
    "width": number;
    "height": number;
    "scale": number;
    "imagePath": string;
    "offsetTop": number;
    "offsetRight": number;
    "offsetBottom": number;
    "offsetLeft": number;
    "createdAt": time$0.Time;

    /** Creates a new ImageTemplate instance. */
    constructor($$source: Partial<ImageTemplate> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("scale" in $$source)) {
            this["scale"] = 0;
        }
        if (!("imagePath" in $$source)) {
            this["imagePath"] = "";
        }
        if (!("offsetTop" in $$source)) {
            this["offsetTop"] = 0;
        }
        if (!("offsetRight" in $$source)) {
            this["offsetRight"] = 0;
        }
        if (!("offsetBottom" in $$source)) {
            this["offsetBottom"] = 0;
        }
        if (!("offsetLeft" in $$source)) {
            this["offsetLeft"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageTemplate instance from a string or object.
     */
    static createFrom($$source: any = {}): ImageTemplate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageTemplate($$parsedSource as Partial<ImageTemplate>);
    }
}

/**
 * LoginConfig 登录配置
 */
export class LoginConfig {
    "url": string;
    "username": string;
    "password": string;

    /**
     * 任务完成后是否保持浏览器开启
     */
    "keepBrowserOpen": boolean;

    /** Creates a new LoginConfig instance. */
    constructor($$source: Partial<LoginConfig> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("keepBrowserOpen" in $$source)) {
            this["keepBrowserOpen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): LoginConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoginConfig($$parsedSource as Partial<LoginConfig>);
    }
}

/**
 * MaterialInfo 用于接收前端传递的素材信息
 */
export class MaterialInfo {
    /**
     * 素材图片 URL
     */
    "url": string;

    /**
     * 素材编号
     */
    "code": string;

    /** Creates a new MaterialInfo instance. */
    constructor($$source: Partial<MaterialInfo> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("code" in $$source)) {
            this["code"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MaterialInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MaterialInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MaterialInfo($$parsedSource as Partial<MaterialInfo>);
    }
}

/**
 * ProductInfo 商品信息（店小秘平台）
 */
export class ProductInfo {
    /**
     * 中文标题
     */
    "titleCh": string;

    /**
     * 英文标题
     */
    "titleEn": string;

    /**
     * 本地图片路径列表
     */
    "imagePaths": string[];

    /**
     * 产品素材图路径
     */
    "materialImg": string;

    /** Creates a new ProductInfo instance. */
    constructor($$source: Partial<ProductInfo> = {}) {
        if (!("titleCh" in $$source)) {
            this["titleCh"] = "";
        }
        if (!("titleEn" in $$source)) {
            this["titleEn"] = "";
        }
        if (!("imagePaths" in $$source)) {
            this["imagePaths"] = [];
        }
        if (!("materialImg" in $$source)) {
            this["materialImg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProductInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProductInfo {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("imagePaths" in $$parsedSource) {
            $$parsedSource["imagePaths"] = $$createField2_0($$parsedSource["imagePaths"]);
        }
        return new ProductInfo($$parsedSource as Partial<ProductInfo>);
    }
}

/**
 * TemplateInfo 用于接收前端传递的模板信息
 */
export class TemplateInfo {
    "id": string;
    "name": string;
    "width": number;
    "height": number;
    "scale": number;
    "imagePath": string;
    "url": string;
    "offset_x": number;
    "offset_y": number;

    /** Creates a new TemplateInfo instance. */
    constructor($$source: Partial<TemplateInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("scale" in $$source)) {
            this["scale"] = 0;
        }
        if (!("imagePath" in $$source)) {
            this["imagePath"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("offset_x" in $$source)) {
            this["offset_x"] = 0;
        }
        if (!("offset_y" in $$source)) {
            this["offset_y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TemplateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemplateInfo($$parsedSource as Partial<TemplateInfo>);
    }
}

/**
 * UploadResult 上传结果
 */
export class UploadResult {
    "success": boolean;
    "message": string;
    "url"?: string;

    /** Creates a new UploadResult instance. */
    constructor($$source: Partial<UploadResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadResult($$parsedSource as Partial<UploadResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
